services:
  - type: web
    name: PiroAutoFilterBot
    env: python
    startCommand: python3 bot.py
    buildCommand: pip3 install -U -r requirements.txt
    repo: https://github.com/ritheshrkrm/PiroAutoFilterBot.git
    region: oregon
    plan: free
    branch: master
    numInstances: 1
    healthCheckPath: /
